name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Build with Maven
        run: mvn -B clean package

      - name: Convert zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r target/Lambda-1.0-SNAPSHOT.zip target/Lambda-1.0-SNAPSHOT.jar

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: deploy to Lambda
        run: |
          aws lambda invoke \
            --function-name auth \
            --invocation-type Event \
            --cli-binary-format raw-in-base64-out
            --zip-file target/Lambda-1.0-SNAPSHOT.zip
            --outfile response.txt
